apiVersion: v1
kind: Service
metadata:
  name: udagram-api-feed
  labels:
    service: udagram-api-feed
spec:
  selector:
    service: udagram-api-feed
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080